import { relations } from "drizzle-orm";
import {
  boolean,
  date,
  integer,
  jsonb,
  pgEnum,
  pgTable,
  text,
  time,
  timestamp,
  uuid,
} from "drizzle-orm/pg-core";

// ============================================================================
// Enums
// ============================================================================

export const userRoleEnum = pgEnum("user_role", [
  "admin",
  "manager",
  "analyst",
  "examiner",
]);

export const caseStatusEnum = pgEnum("case_status", [
  "new",
  "in_progress",
  "blocked",
  "resolved",
]);

export const casePriorityEnum = pgEnum("case_priority", [
  "low",
  "medium",
  "high",
]);

// ============================================================================
// User Profiles (extends neon_auth.users)
// ============================================================================

export const userProfiles = pgTable("user_profiles", {
  id: uuid("id").primaryKey().defaultRandom(),
  userId: text("user_id").notNull().unique(), // References neon_auth.users.id
  badgeNumber: text("badge_number").unique(),
  role: userRoleEnum("role").notNull().default("examiner"),
  active: boolean("active").notNull().default(true),
  createdAt: timestamp("created_at").notNull().defaultNow(),
  updatedAt: timestamp("updated_at")
    .notNull()
    .defaultNow()
    .$onUpdate(() => new Date()),
});

// ============================================================================
// Clients
// ============================================================================

export const clients = pgTable("clients", {
  id: uuid("id").primaryKey().defaultRandom(),
  name: text("name").notNull(),
  contactEmail: text("contact_email"),
  contactPhone: text("contact_phone"),
  address: text("address"),
  notes: text("notes"),
  createdAt: timestamp("created_at").notNull().defaultNow(),
  updatedAt: timestamp("updated_at")
    .notNull()
    .defaultNow()
    .$onUpdate(() => new Date()),
});

// ============================================================================
// Cases
// ============================================================================

export const cases = pgTable("cases", {
  id: uuid("id").primaryKey().defaultRandom(),
  caseNumber: text("case_number").unique(), // Generated by application
  title: text("title").notNull(),
  clientId: uuid("client_id").references(() => clients.id, {
    onDelete: "set null",
  }),
  description: text("description"),
  status: caseStatusEnum("status").notNull().default("new"),
  priority: casePriorityEnum("priority").default("medium"),
  incidentDate: date("incident_date"),
  incidentTime: time("incident_time"),
  assignedTo: text("assigned_to"), // References neon_auth.users.id
  createdBy: text("created_by").notNull(), // References neon_auth.users.id
  createdAt: timestamp("created_at").notNull().defaultNow(),
  updatedAt: timestamp("updated_at")
    .notNull()
    .defaultNow()
    .$onUpdate(() => new Date()),
});

// ============================================================================
// Evidence
// ============================================================================

export const evidence = pgTable("evidence", {
  id: uuid("id").primaryKey().defaultRandom(),
  caseId: uuid("case_id")
    .notNull()
    .references(() => cases.id, { onDelete: "cascade" }),
  name: text("name").notNull(),
  description: text("description"),
  fileUrl: text("file_url"),
  fileType: text("file_type"),
  fileSize: integer("file_size"),
  chainOfCustody: text("chain_of_custody"),
  uploadedBy: text("uploaded_by").notNull(), // References neon_auth.users.id
  createdAt: timestamp("created_at").notNull().defaultNow(),
});

// ============================================================================
// Case Notes
// ============================================================================

export const caseNotes = pgTable("case_notes", {
  id: uuid("id").primaryKey().defaultRandom(),
  caseId: uuid("case_id")
    .notNull()
    .references(() => cases.id, { onDelete: "cascade" }),
  content: text("content").notNull(),
  authorId: text("author_id").notNull(), // References neon_auth.users.id
  createdAt: timestamp("created_at").notNull().defaultNow(),
  updatedAt: timestamp("updated_at")
    .notNull()
    .defaultNow()
    .$onUpdate(() => new Date()),
});

// ============================================================================
// Audit Log
// ============================================================================

export const auditLog = pgTable("audit_log", {
  id: uuid("id").primaryKey().defaultRandom(),
  userId: text("user_id").notNull(), // References neon_auth.users.id
  userEmail: text("user_email").notNull(), // Denormalized for historical record
  userName: text("user_name"), // Denormalized for historical record
  action: text("action").notNull(), // e.g., "case.created", "evidence.uploaded"
  entityType: text("entity_type").notNull(), // e.g., "case", "evidence", "client"
  entityId: uuid("entity_id"),
  changes: jsonb("changes"), // { before: {...}, after: {...} }
  ipAddress: text("ip_address"),
  createdAt: timestamp("created_at").notNull().defaultNow(),
});

// ============================================================================
// Relations
// ============================================================================

export const clientsRelations = relations(clients, ({ many }) => ({
  cases: many(cases),
}));

export const casesRelations = relations(cases, ({ one, many }) => ({
  client: one(clients, {
    fields: [cases.clientId],
    references: [clients.id],
  }),
  evidence: many(evidence),
  notes: many(caseNotes),
}));

export const evidenceRelations = relations(evidence, ({ one }) => ({
  case: one(cases, {
    fields: [evidence.caseId],
    references: [cases.id],
  }),
}));

export const caseNotesRelations = relations(caseNotes, ({ one }) => ({
  case: one(cases, {
    fields: [caseNotes.caseId],
    references: [cases.id],
  }),
}));

// ============================================================================
// Types
// ============================================================================

export type UserProfile = typeof userProfiles.$inferSelect;
export type NewUserProfile = typeof userProfiles.$inferInsert;

export type Client = typeof clients.$inferSelect;
export type NewClient = typeof clients.$inferInsert;

export type Case = typeof cases.$inferSelect;
export type NewCase = typeof cases.$inferInsert;

export type Evidence = typeof evidence.$inferSelect;
export type NewEvidence = typeof evidence.$inferInsert;

export type CaseNote = typeof caseNotes.$inferSelect;
export type NewCaseNote = typeof caseNotes.$inferInsert;

export type AuditLogEntry = typeof auditLog.$inferSelect;
export type NewAuditLogEntry = typeof auditLog.$inferInsert;

export type UserRole = "admin" | "manager" | "analyst" | "examiner";
export type CaseStatus = "new" | "in_progress" | "blocked" | "resolved";
export type CasePriority = "low" | "medium" | "high";
